const books = [
    { title: "Bagëti e Bujqësi. Lulet e Verës", author: "Naim Frashëri", category: "poezi", quantity: 33, price: 150, icon: "bagetia_e_bujqesia_lulet_e_veres.jpg" },
    { title: "Visare të letërsisë shqiptare 3", author: "Naim Frashëri", category: "antologji", quantity: 1, price: 800, icon: "visare_te_letersise_shqiptare.jpeg" },
    { title: "Visare të letërsisë shqiptare 2,4,5,6", author: "Naim Frashëri", category: "antologji", quantity: 4, price: 600, icon: "visare_te_letersise_shqiptare.jpeg" },
    { title: "Vepra 2-20", author: "Ismail Kadare", category: "roman", quantity: 19, price: 700, icon: "vepra_2_20.jpeg" },
    { title: "Pallati i ëndrrave", author: "Ismail Kadare", category: "roman", quantity: 1, price: 700, icon: "pallati_i_enderrave.jpeg" },
    { title: "Lulet e verës", author: "Naim Frashëri", category: "poezi", quantity: 2, price: 400, icon: "lulet_e_veres.jpeg" },
    { title: "Naim Frashëri", author: "Dhimitër Shukeriqi", category: "biografi", quantity: 2, price: 4, icon: "naim_frasheri.jpeg" },
    { title: "Këngët e Milosaos", author: "Jeronim de Rada", category: "epikë / klasikë", quantity: 29, price: 200, icon: "kenget_e_milosaos.jpeg" },
    { title: "Poezi të zgjedhura", author: "Naim Frashëri", category: "poezi të zgjedhura", quantity: 3, price: 1.50, icon: "poezi_te_zgjedhura_1.jpeg" },
    { title: "Historia e Skënderbeut", author: "Naim Frashëri", category: "epikë / klasikë", quantity: 19, price: 350, icon: "histori_e_skenderbeut.jpg" },
    { title: "Tradhëtia", author: "Kapllan Resuli", category: "roman", quantity: 28, price: 520, icon: "tradhetia_.jpg" },
    { title: "Gjiri i virgjëreshës", author: "Arben Duka", category: "poezi", quantity: 20, price: 600, icon: "gjiri_i_virgjereshes.jpg" },
    { title: "Poezi të zgjedhura", author: "Asdreni", category: "poezi të zgjedhura", quantity: 30, price: 420, icon: "poezi_te_zgjedhura_2.jpeg" },
    { title: "Juvenilja dhe vjersha të tjera", author: "Ndre Mjeda", category: "poezi", quantity: 4, price: 320, icon: "juvenilia_dhe_vjersha_te_tjera.jpeg" },
    { title: "Tregime të moçme shqiptare", author: "Mitrush Kuteli", category: "novela / tregime", quantity: 3, price: 450, icon: "tregime_te_mocme_shqipate.jpeg" },
    { title: "Bardha e Temalit", author: "Pashko Vasa", category: "roman", quantity: 22, price: 350, icon: "bardha_e_temalit.jpeg" },
    { title: "Kanuni dhe koha e sotme", author: "Ndue Dedaj", category: "studim / ese", quantity: 3, price: null, icon: "kanuni_dhe_koha_e_sotme.jpeg" },
    { title: "Kënga e sprasme e Balës", author: "Gavril Dara I Riu", category: "epikë / klasikë", quantity: 33, price: 250, icon: "kenga_e_sprasme_e_bales.jpeg" },
    { title: "Album", author: "Fan Noli", category: "poezi", quantity: 29, price: 400, icon: "album.jpeg" },
    { title: "Vargje të lira", author: "Migjeni", category: "poezi", quantity: 16, price: 200, icon: "vargje_te_lira.jpeg" },
    { title: "Guna e Zezë", author: "Gaqo Bushaka", category: "roman", quantity: 28, price: 300, icon: "guna_e_zeze.jpeg" },
    { title: "Shtjellat e bardha", author: "Ramadan Pasmaciu", category: "poezi", quantity: 12, price: 300, icon: "shtjellat_e_bardha.jpeg" },
    { title: "Poezi të zgjedhura", author: "Ali Asllani", category: "poezi të zgjedhura", quantity: 29, price: 460, icon: "poezi_te_zgjedhura_3.jpg" },
    { title: "Novelat e qytetit të Veriut", author: "Migjeni", category: "novela / tregime", quantity: 25, price: 220, icon: "novelat_e_qytetit_te_veriut.jpeg" },
    { title: "Melodia e valës së kaltër", author: "Ermal Lala", category: "poezi", quantity: 2, price: 500, icon: "melodia_e_vales_se_kalter.jpg" },
    { title: "Antologji", author: "Anton Papleka", category: "antologji", quantity: 28, price: 480, icon: "antologji.jpeg" },

    { title: "Fjala dhe heshtja", author: "Anton Nazeku", category: "poezi", quantity: 5, price: 1000, icon: "fjala_dhe_heshtja.jpeg" },
    { title: "Poezi", author: "Zef Serembe", category: "poezi", quantity: 35, price: 150, icon: "poezi.jpeg" },
    { title: "Toka e përgjakur", author: "Nazmi Rrahmani", category: "roman", quantity: 30, price: 520, icon: "toka_e_pergjakur.jpeg" },
    { title: "Kush rron duke shpresuar", author: "Ramadan Pasmaciu", category: "poezi", quantity: 21, price: 500, icon: "kush_rron_duke_shpresuar.jpeg" },
    { title: "Shqipëria, ç'ka qenë, ç’është …", author: "Sami Frashëri", category: "studim / ese", quantity: 27, price: 280, icon: "shqiperia_cka_qene_ceshte.jpeg" },
    { title: "Mbi letërsinë e arbëreshëve të Italisë", author: "Anton Berisha", category: "studim / ese", quantity: 29, price: 520, icon: "mbi_letersine_e_arberesheve_te_italise.jpeg" },
    { title: "Mëngjesi i së nesërmes", author: "Adem Istrefi", category: "roman", quantity: 1, price: 210, icon: "mengjesi_i_se_nesermes.jpeg" },
    { title: "Zhvarrosja e një dashurie", author: "Virgjil Muçi", category: "roman", quantity: 1, price: 3.50, icon: "zhvarrosja_e_nje_dashurie.jpeg" },
    { title: "E pakryer", author: "Preç Zogaj", category: "poezi", quantity: 1, price: 3, icon: "e_pakryer.jpeg" },
    { title: "Poezia Shqipe", author: "Ali Asllani", category: "poezi", quantity: 1, price: 2, icon: "poezi_te_zgjedhura_3.jpg" },
    { title: "Buka e një stine me borë ", author: "Koço Kosta", category: "roman", quantity: 1, price: 6.50, icon: "buka_E_nje_stine_me_bore.jpeg" },
    { title: "Zani i Naltë", author: "Revistë shkencore,kulturore", category: "revistë", quantity: 1, price: 300, icon: "zani_i_nalte.jpeg" },
    { title: "Te dheu i huaj", author: "Zef Sikroi", category: "roman", quantity: 2, price: 450, icon: "te_dheu_i_huaj.jpeg" },
    { title: "Kënga e sprapsme e Balës", author: "Gavril Dara I Riu", category: "epikë / klasikë", quantity: 1, price: 800, icon: "kenga_e_sprasme_e_bales.jpeg" },
    { title: "Vrasja e Lulit të vocërr", author: "Bedri Islami", category: "roman", quantity: 13, price: 500, icon: "vrasja_e_lulit_te_vocerr.jpeg" },
    { title: "Magjia e Rilindjes Kombëtare", author: "Albert Frashëri", category: "studim / ese", quantity: 3, price: 600, icon: "magjia_e_rilindjes_kombetare.jpeg" },
    { title: "Hija në murin e kishës", author: "Aqif Malaj", category: "roman", quantity: 5, price: 700, icon: "hija_ne_murin_e_kishes.jpeg" },
    { title: "Peizazh", author: "Faik Konica", category: "publicistikë", quantity: 2, price: 600, icon: "📖" },
    { title: "Shtjellat e bardha", author: "Ramadan Pasmaciu", category: "poezi", quantity: 17, price: 350, icon: "shtjellat_e_bardha.jpeg" },
    { title: "201 kryefabula", author: "Ferit Lamaj", category: "poezi", quantity: 23, price: 400, icon: "201_kryefabula.jpeg" },
    { title: "Ara në mal", author: "Petro Marko", category: "roman", quantity: 6, price: 5, icon: "ara_ne_mal.jpeg" },
    { title: "Të dua", author: "Françesko Alberoni", category: "studim / ese", quantity: 19, price: 500, icon: "te_dua.jpeg" },
    { title: "Doktor Gjilpëra", author: "Faik Konica", category: "roman", quantity: 27, price: 500, icon: "doktor_gjilpera.jpeg" },
    { title: "Nata e Ustikës", author: "Petro Marko", category: "roman", quantity: 18, price: 350, icon: "nata_e_ustikes.jpg" },
    { title: "Oliver Tuist", author: "Çarls Dikens", category: "roman", quantity: 28, price: 590, icon: "oliver_tuist.jpg" },
    { title: "Vetëm një herë në jetë", author: "Daniel Stiell", category: "roman", quantity: 20, price: 500, icon: "vetem_nje_here_ne_jete.jpeg" },
    { title: "Diplomati", author: "Harilla Goga", category: "studim / ese", quantity: 2, price: 400, icon: "diplomati.jpeg" },
    { title: "Shansi i fundit në fillim të shekullit", author: "Bedri Islami", category: "publicistikë", quantity: 13, price: 500, icon: "shansi_i_fundit_ne_fillim_te_shekullit.jpeg" },
    { title: "Mallkimi i shkronjave shqipe", author: "Petro N. Luarasi", category: "studim / ese", quantity: 28, price: 380, icon: "mallkimi_i_shkronjave_shqipe.jpeg" },
    { title: "Gjenerali në labirintin e vet", author: "Gabriel Marquez", category: "roman", quantity: 28, price: 600, icon: "gjenerali_ne_labirintin_e_tij.jpeg" },
    { title: "Beteja", author: "Patrick Ramboul", category: "roman", quantity: 29, price: 760, icon: "beteja.jpeg" },
    { title: "Sofokliu në prozë", author: "Jenis Renekos", category: "epikë / klasikë", quantity: 31, price: 250, icon: "sofokli_ne_proze.jpeg" },
    { title: "Tartarini i Toroskonit", author: "Alphonse Daudet", category: "roman", quantity: 5, price: 400, icon: "tartarini_i_toroskonit.jpeg" },
    { title: "Në rrethinat e Parisit", author: "Guy de Moupoussont", category: "novela / tregime", quantity: 4, price: 600, icon: "ne_rrathinat_e_parisit.jpeg" },
    { title: "Mëzi i kuq", author: "Xhon Steinbek", category: "roman", quantity: 3, price: 250, icon: "mezi_i_kuq.jpeg" },
    { title: "Njeriu që qesh", author: "Viktor Hygo", category: "roman", quantity: 24, price: 620, icon: "njeriu_qe_qesh.jpg" },
    { title: "E bukura Margaret", author: "Rajder Hoggard", category: "roman", quantity: 17, price: 450, icon: "e_bukura_margaret.jpg" },
    { title: "Komedia Hyjnore, Ferri", author: "Dante Aligeri", category: "epikë / klasikë", quantity: 2, price: 500, icon: "komedia_hyjnore_ferri.jpg" },
    { title: "Ana Karenina", author: "Lev Tolstoi", category: "roman", quantity: 2, price: 1100, icon: "ana_karenina.jpg" },
    { title: "Eskili ne prozë", author: "Janis Benekos", category: "epikë / klasikë", quantity: 1, price: 350, icon: "eskili_ne_proze.jpeg" },
    { title: "Euripidi ne prozë", author: "Janis Benekos", category: "epikë / klasikë", quantity: 1, price: 7, icon: "euripidi_ne_proze.jpeg" },
    { title: "Euripidi ne prozë", author: "Janis Benekos", category: "epikë / klasikë", quantity: 31, price: 250, icon: "euripidi_ne_proze.jpeg" },

    { title: "Zemra", author: "Edmond de Amicis", category: "roman", quantity: 27, price: 250, icon: "zemra.jpeg" },
    { title: "Iliada", author: "Homeri", category: "epikë / klasikë", quantity: 2, price: 2000, icon: "iliada.jpeg" },
    { title: "Çajld Haroldi", author: "Xhorxh Gordon Bajron", category: "poezi", quantity: 2, price: 800, icon: "xhorxh_gordn.jpg" },
    { title: "Politika dhe demokracia", author: "Kval-Mellbye-Tranoy", category: "studim / ese", quantity: 3, price: null, icon: "politika_dhe_demokracia.jpeg" },
    { title: "E bardhë, e brishtë, si kristal", author: "Thanas Jorgji", category: "roman", quantity: 15, price: 600, icon: "e_bardhe_e_brishte.jpeg" },
    { title: "Poezi të zgjedhura", author: "33 poete franceze", category: "antologji", quantity: 27, price: 400, icon: "33_poete_franceze.jpeg" },
    { title: "Dramat në prozë", author: "Fridrih Shiler", category: "drama", quantity: 25, price: 540, icon: "dramat_ne_proze.jpeg" },
    { title: "Tregtari i Venedikut", author: "Shekspir", category: "drama", quantity: 32, price: 440, icon: "tregtari_i_venedikut.jpg" },
    { title: "Lulet e mollës", author: "John Galsworthy", category: "roman", quantity: 5, price: 300, icon: "lulet_e_molles.jpeg" },
    { title: "Njerëzit e mjegullës", author: "Henri Haggard", category: "roman", quantity: 5, price: 350, icon: "njerezit_e_mjegulles.jpeg" },
    { title: "Rikardi II", author: "Shekspir", category: "drama", quantity: 34, price: 550, icon: "rikardi_II.jpeg" },
    { title: "Thesaret e mbretit Solomon", author: "Henri Haggard", category: "roman", quantity: 22, price: 600, icon: "Thesaret_e_mbretit_Solomon.jpeg" },
    { title: "Viti I vdekjes së Rikardi Reisit", author: "Jose Soramango", category: "roman", quantity: 28, price: 690, icon: "Viti_I_vdekjes_se_Rikardi_Reisit.jpeg" },
    { title: "Poezi", author: "Borges", category: "poezi", quantity: 27, price: 500, icon: "borhes.jfif" },
    { title: "Poezi të zgjedhura", author: "Arthur Rimbaud", category: "poezi të zgjedhura", quantity: 30, price: 230, icon: "poezi_te_zgjedhura_4.jpeg" },
    { title: "David Koperfild", author: "Çarles Dickens", category: "roman", quantity: 5, price: 450, icon: "david_koperfildi.jpeg" },
    { title: "Këngë", author: "Xhakomo Leopardi", category: "poezi", quantity: 1, price: 900, icon: "kenge.jpeg" },
    { title: "Tej fasadës", author: "Arcibald Kronin", category: "roman", quantity: 9, price: 250, icon: "tej_fasades.jpeg" },
    { title: "Gloria Victis", author: "Fatos Arapi", category: "poezi", quantity: 20, price: 200, icon: "gloria_victis.jpeg" },
    { title: "Të humburit në oqean", author: "Majn Rid", category: "roman", quantity: 19, price: 500, icon: "Te_humburit_ne_oqean.jpeg" },
    { title: "Unë e dua jetën", author: "Alan Marshall", category: "roman", quantity: 8, price: 400, icon: "📖" },
    { title: "Sherlock Holmes", author: "Conon Doyle", category: "novela / tregime", quantity: 5, price: 350, icon: "sherlok_holms.jpeg" },
    { title: "Perla", author: "Xhon Steinbek", category: "roman", quantity: 3, price: 300, icon: "perla.jpeg" },
    { title: "Rob Roi", author: "Valter Skot", category: "roman", quantity: 17, price: 300, icon: "rob_roi.jpeg" },
    { title: "Dhëmbi i Bardhë", author: "Xhek London", category: "roman", quantity: 29, price: 340, icon: "dhembi_i_bardhe.jpeg" },
    { title: "Duaje emrin tënd", author: "Nasi Lera", category: "roman", quantity: 23, price: 300, icon: "duaje_emrin_tend.jpeg" },
    { title: "Rroke ditën", author: "Sawl Bellow", category: "roman", quantity: 27, price: 420, icon: "rroke_diten.jpeg" },
    { title: "Të fshehtat e kimisë", author: "Enciklopedi", category: "enciklopedi", quantity: 5, price: 400, icon: "te_fshehtat_e_kimise.jpeg" },
    { title: "Magjia e sportit", author: "Enciklopedi", category: "enciklopedi", quantity: 7, price: 400, icon: "magjia_e_sportit.jpeg" },
    { title: "Kalorësit e Mesjetës", author: "Enciklopedi", category: "enciklopedi", quantity: 9, price: 320, icon: "kaloresit_e_mesjetes.jpeg" },
    { title: "Thesaret e letërsisë", author: "Enciklopedi", category: "enciklopedi", quantity: 35, price: 400, icon: "thesaret_e_letersise.jpeg" },
    { title: "Fjalë prej zjarri Kosovë", author: "Poetë nga Kosova", category: "poezi", quantity: 28, price: 500, icon: "Fjale_prej_zjarri_Kosove.jpg" },
    { title: "Tartarini i Toroskonit", author: "Alfons Dode", category: "roman", quantity: 17, price: 300, icon: "tartarini_i_toroskonit.jpeg" },
    { title: "Ferrparajsa", author: "Xhevahir Spahiu", category: "poezi", quantity: 26, price: 300, icon: "Ferrparajsa.jpeg" },
    { title: "Apologjia e vërtetë e Sokratit", author: "Kostas Varnals", category: "studim / ese", quantity: 26, price: 290, icon: "Ideologjia_e_vertete_e_sokratit.jpg" },
    { title: "Befasitë e matematikës", author: "Enciklopedi", category: "enciklopedi", quantity: 36, price: 400, icon: "befasite_e_matematikes.jpeg" },
    { title: "Enciklopedi e mendimit", author: "Ndricim Kulla", category: "studim / ese", quantity: 2, price: 1800, icon: "Enciklopedi_e_mendimit.jpeg" },
    { title: "Të fshehtat e kimisë", author: "", category: "enciklopedi", quantity: 5, price: 400, icon: "te_fshehtat_e_kimise.jpeg" },
    { title: "Kalorësit e Mesjetës", author: "", category: "enciklopedi", quantity: 1, price: 320, icon: "kaloresit_e_mesjetes.jpeg" },
    { title: "Due di due", author: "Andrea De Carlo", category: "roman", quantity: 1, price: 7.30, icon: "dua_te_di.jpeg" },
    { title: "Si të aftësohemi për provimet", author: "Shpresa Partela", category: "studim / ese", quantity: 1, price: null, icon: "si_te_aftesohemi_per.jpeg" },
    { title: "Historia e arsimit", author: "", category: "histori", quantity: 1, price: null, icon: "historia_e_arsimit.jpeg" },
    { title: "Revistë pedagogjike", author: "Fabrice Herviou-Wane", category: "revistë", quantity: 1, price: 1000, icon: "reviste_pedagogjike.jpeg" },
    { title: "Guidë për Maturën Shtetërore", author: "Ministria e Arsimit", category: "studim / ese", quantity: 1, price: null, icon: "guide_per_maturen_shteterore.jpeg" },
    { title: "Science", author: "Adison Wesley", category: "studim / ese", quantity: 1, price: null, icon: "science.jfif" },
    { title: "Portofol", author: "-", category: "studim / ese", quantity: 2, price: 500, icon: "portofol.jpeg" },
    { title: "Njohuri për biznesin", author: "Junior Achivement", category: "studim / ese", quantity: 21, price: 200, icon: "njohuri_per_biznesin.jpeg" },
    { title: "Platform 4", author: "Kate Leight", category: "studim / ese", quantity: 1, price: 453, icon: "platform_4.jpeg" },
    { title: "New framework", author: "Grill Holley", category: "studim / ese", quantity: 2, price: null, icon: "new_framework.jpeg" },
    { title: "Platform 3(Wb)", author: "Janathan Mellor", category: "studim / ese", quantity: 1, price: null, icon: "platform_3.jpeg" },
    { title: "Focus 4", author: "Daniel Broyshow", category: "studim / ese", quantity: 4, price: 455, icon: "focus_4.jpeg" },
    { title: "L’italiano per stanieri 1, 2", author: "Bonacci editore", category: "studim / ese", quantity: 4, price: null, icon: "📖" },
    { title: "Shoqërite e nxënësve", author: "JA", category: "studim / ese", quantity: 1, price: 160, icon: "shoqerite_e_nxenesve.jpeg" },
    { title: "Mësuesi", author: "Xhon Djui", category: "studim / ese", quantity: 1, price: 100, icon: "📖" },
    { title: "Platform 2", author: "Kate Leigh", category: "studim / ese", quantity: 1, price: null, icon: "platform_2.jpeg" },
    { title: "Emira", author: "Anton Santori", category: "roman", quantity: 1, price: 800, icon: "emira.jpeg" },
    { title: "Tre mjeshtër", author: "Stefan Cvajg", category: "studim / ese", quantity: 1, price: 1000, icon: "Tre_mjeshter.jpeg" },
    { title: "Gabimi", author: "Antonis Samaraqis", category: "roman", quantity: 1, price: 5, icon: "gabimi.jpeg" },
    { title: "Procesi", author: "Franz Kafka", category: "roman", quantity: 1, price: 790, icon: "procesi.jpeg" },
    { title: "Ishuj në qiell", author: "Artur Klark", category: "roman", quantity: 1, price: 6, icon: "Ishuj_ne_Qiell.jpeg" },
    { title: "Net të Bardha", author: "Fjodor Dostojevski", category: "novela / tregime", quantity: 1, price: 500, icon: "net_te_bardha.jpeg" },
    { title: "Mizantropi", author: "Molier", category: "drama", quantity: 1, price: 500, icon: "mizantropi.jpeg" },
    { title: "Vilhelm Teli", author: "Frederik Shiler", category: "drama", quantity: 1, price: 800, icon: "vilhem_teli.jpeg" },
    { title: "Epi i Gilameshit", author: "Anton Berisha", category: "epikë / klasikë", quantity: 1, price: 600, icon: "Epi_i_Gilameshit.jpeg" },
    { title: "Loja", author: "Teodor Keko", category: "roman", quantity: 1, price: 5.50, icon: "loja.jfif" },
    { title: "Vite mbi supe", author: "Kiço Blushi", category: "studim / ese", quantity: 1, price: 7, icon: "vite_mbi_supe.webp" },
    { title: "Romeo dhe Zhulieta", author: "Shekspir", category: "drama", quantity: 1, price: 500, icon: "Romeo_dhe_Zhulieta.jpeg" },
    { title: "Lufta e Trojës", author: "Kujtim Ymeri", category: "epikë / klasikë", quantity: 1, price: 400, icon: "Lufta_e_Trojes.jpeg" },
    { title: "Plaku dhe deti", author: "Ernest Heminguej", category: "roman", quantity: 1, price: 400, icon: "Plaku_dhe_deti.jpeg" },
    { title: "Katedralja e Parisit", author: "Viktor Hygo", category: "roman", quantity: 1, price: 1200, icon: "Katedralja_e_Parisit.jpeg" },
    { title: "Eugjen Onjegini", author: "A.S Pushkin", category: "roman", quantity: 1, price: 500, icon: "Eugjen_Onjegini.jpeg" },
    { title: "14 novela", author: "Anton Çehov", category: "novela / tregime", quantity: 1, price: 700, icon: "14_novela.jpg" },
    { title: "Jul Çezari", author: "Shekspir", category: "drama", quantity: 3, price: 550, icon: "jul-cezari-uiliam-shekspir.jpg" },
    { title: "Pranvera e Pragës", author: "Jani Guxo", category: "histori", quantity: 2, price: 600, icon: "pranvera_e_prages.jpeg" },
    { title: "Pse", author: "Sterjo Spasse", category: "roman", quantity: 2, price: 450, icon: "pse.jpg" },
    { title: "Zbulimet e Sherlock Holmesit", author: "Arthur Doyle", category: "novela / tregime", quantity: 3, price: 300, icon: "Zbulimet_e_Sherlock_Holmesit.jpg" },

    { title: "Vesa mbi këngë", author: "Timo Merkuri", category: "studim / ese", quantity: 2, price: 600, icon: "Vesa_mbi_kenge.jpg" },
    { title: "Majat e Shalës", author: "Rose Lane", category: "histori", quantity: 1, price: 700, icon: "majat-e-shales-rose-wilder-lane.jpg" },
    { title: "Panairi i kotësive", author: "Uilliam Theker", category: "roman", quantity: 1, price: 1250, icon: "panairi-i-kotesive.jpg" },
    { title: "Metamorfoza", author: "Franz Kafka", category: "novela / tregime", quantity: 6, price: 500, icon: "metamorfoza.jpg" },
    { title: "Uri prej ujku", author: "Ezopi", category: "novela / tregime", quantity: 1, price: 420, icon: "fabulat-e-ezopit-uri-prej-ujku.jpg" },
    { title: "Vegime letrare", author: "", category: "studim / ese", quantity: 1, price: 250, icon: "vegime_letrare.jpeg" },
    { title: "Enciklopedi e mendimit shqiptar", author: "Ndricim Kulla", category: "studim / ese", quantity: 2, price: 1800, icon: "Enciklopedi_e_mendimit.jpeg" },
    { title: "Antologji e mendimit shqiptar", author: "Ndricim Kulla", category: "antologji", quantity: 2, price: 1500, icon: "Enciklopedi_e_mendimit.jpeg" },
    { title: "La lingua pensata", author: "Daniela Bertocchi", category: "studim / ese", quantity: 1, price: 1660, icon: "La_lingua_pensata.jpg" },
    { title: "Treasury of Literature", author: "", category: "antologji", quantity: 1, price: null, icon: "📖" },
    { title: "Insciallah", author: "Oriana Fallaci", category: "roman", quantity: 1, price: 930, icon: "Insciallah.jpg" },
    { title: "Vepra", author: "Branko Merxhani", category: "publicistikë", quantity: 1, price: 1000, icon: "vepra-branko-merxhani.jpg" },
    { title: "Il dubbio", author: "Luciano de Cresncenzo", category: "roman", quantity: 1, price: 420, icon: "Il_dubbio.jpg" },
    { title: "Sistemi rasor i emrave të shqipes", author: "Kolec Topalli", category: "studim / ese", quantity: 1, price: 1000, icon: "sistemi-rasor-i-emrave-te-shqipes-kolec-topalli.jpg" },
    { title: "Poezia Vepra 1", author: "Lasgush Poradeci", category: "poezi", quantity: 1, price: 1500, icon: "poezia-vepra-i-lasgush-poradeci.jpg" },
    { title: "Kandili i Kuq", author: "Faik Konica", category: "roman", quantity: 1, price: 1200, icon: "Kandili_i_Kuq.jpeg" },
    { title: "Brenga e Ballkanit", author: "Edith Durhan", category: "histori", quantity: 1, price: 1000, icon: "brenga-e-ballkanit-edith-durham.jpg" },
    { title: "Vazabolario Bella Lingua Italiana", author: "Nicola Zingarelli", category: "enciklopedi", quantity: 2, price: 2250, icon: "Vazabolario_Bella_Lingua_Italiana.jpg" },
    { title: "Xha Gorioi", author: "Honore de Balzak", category: "roman", quantity: 6, price: 1000, icon: "xha-gorioi-honore-de-balzak.jpg" },
    { title: "Fjalor themelor Rusisht-Shqip", author: "", category: "enciklopedi", quantity: 4, price: 350, icon: "fjalor_themelor_rusisht_shqip.jpeg" },
    { title: "Kryefabula", author: "Ferit Lamaj", category: "poezi", quantity: 3, price: 400, icon: "201_kryefabula.jpeg" },
    { title: "Të shkruajmë ese", author: "Mirela Celami", category: "studim / ese", quantity: 13, price: 500, icon: "Te_shkruajme_ese.jpg" },
    { title: "Njohuri për shoqërine", author: "Aida Serjanaj", category: "studim / ese", quantity: 1, price: null, icon: "Gli_Aracini_Di_Montalbano.jpg" },
    { title: "Gjuha Frënge", author: "Violeta Kraja", category: "studim / ese", quantity: 1, price: null, icon: "📖" },
    { title: "Francais debutant 1", author: "", category: "studim / ese", quantity: 2, price: 2100, icon: "francais_debutant_1.jpeg" },
    { title: "Francais debutant 2", author: "", category: "studim / ese", quantity: 1, price: 2100, icon: "francais_debutant_2.jpeg" },
    { title: "Matematikë", author: "Llambri Puka", category: "studim / ese", quantity: 2, price: 500, icon: "matematike.jpeg" },
    { title: "Kurrikula dhe shkolla", author: "", category: "studim / ese", quantity: 1, price: null, icon: "korrikula_dhe_shkolla.jpeg" },
    { title: "Gli Aracini Di Montalbano", author: "Andrea Camilleri", category: "roman", quantity: 1, price: 840, icon: "Gli_Aracini_Di_Montalbano.jpg" },
    { title: "Mastro-don-Gesualdo", author: "Giovanni Verga", category: "roman", quantity: 1, price: 930, icon: "Mastro-don-Gesualdo.jpg" },
    { title: "Marcovaldo", author: "Halo Calvino", category: "novela / tregime", quantity: 1, price: 620, icon: "Marcovaldo.jpg" },
    { title: "Spektri", author: "Leiv Mjeldhim", category: "roman", quantity: 1, price: null, icon: "517-Mjeldhejm-Spektri.png" },
    { title: "Tuttle le cosmicomiche", author: "Italo Calvino", category: "novela / tregime", quantity: 1, price: 930, icon: "Tuttle_le_cosmicomiche.webp" },
    { title: "Shqiptarët dhe hebrenjtë", author: "Shaban Sinani", category: "histori", quantity: 1, price: 1500, icon: "shqiptaret-dhe-hebrenjte-shaban-sinani.jpg" },
    { title: "Rispondimi", author: "Susanna Tamaro", category: "roman", quantity: 1, price: 720, icon: "Rispondimi.jpg" },
    { title: "Castelli di Rabbia", author: "Alessandro Baricco", category: "roman", quantity: 1, price: 780, icon: "Castelli_di_Rabbia.jpg" },
    { title: "Historia e qytetërimit botëror", author: "Etleva Breshani", category: "histori", quantity: 1, price: 200, icon: "historia_e_qyteterimit_boteror.jpeg" },
    { title: "Revista shkencore", author: "", category: "revistë", quantity: 1, price: 300, icon: "reviste_shkencore.jpeg" },
    { title: "Scuola", author: "Gloria Bernardi", category: "studim / ese", quantity: 1, price: null, icon: "scuola.jpeg" },
    { title: "Didattica dell’Italiano a Stranieri", author: "Paolo Balboni", category: "studim / ese", quantity: 1, price: 16, icon: "Didattica_dellItaliano_a_Stranieri.jpg" },

    { title: "La storia d’Italia", author: "De Agostini Ragazzi", category: "histori", quantity: 1, price: 3900, icon: "la_storia_ditalia.jpeg" },
    { title: "L’arte Italiana", author: "Gloria Fosi", category: "histori", quantity: 2, price: 4800, icon: "Larte_Italiana.webp" },
    { title: "Celebrate", author: "", category: "studim / ese", quantity: 1, price: null, icon: "celebrate.jpeg" },
    { title: "Le Regioni d’Italia", author: "", category: "histori", quantity: 1, price: null, icon: "le_regioni_ditalia.jpeg" },
    { title: "Regioni d’Italia", author: "", category: "histori", quantity: 1, price: 1650, icon: "regioni_ditalia.jpeg" },
    { title: "Fjalori i shqipes së sotme", author: "", category: "enciklopedi", quantity: 1, price: 6000, icon: "fjalor_i_shqipes_se_sotme.jpeg" },
    { title: "Il barane rompante", author: "Italo Calvino", category: "roman", quantity: 1, price: 740, icon: "Il_barane_rompante.jpg" },
    { title: "How I trained my Colt", author: "Sandy Rabinowit", category: "studim / ese", quantity: 1, price: null, icon: "How_I_trained_my_Colt.jpg" },
    { title: "Don Camillo", author: "Guareschi", category: "roman", quantity: 1, price: 840, icon: "Guareschi.webp" },
    { title: "Cristo si e fermato a Eboli", author: "Carlo Levi", category: "roman", quantity: 1, price: 800, icon: "Cristo_si_e_fermato_a_Eboli.jpg" },
    { title: "La Donna delle Meraviglie", author: "Alberto Bevilacqua", category: "roman", quantity: 1, price: 740, icon: "La_Donna_delle_Meraviglie.jpg" },
    { title: "Se questo e un uomo la tregua", author: "Primo Levi", category: "histori", quantity: 1, price: 900, icon: "Levi-Primo_Se-questo-è-un-uomo.jpg" },
    { title: "La spiaggia", author: "Cesare Pavese", category: "roman", quantity: 1, price: 723, icon: "spiaga.jpeg" },
    { title: "Cioccolata da Hanselmann", author: "Rosetta Loy", category: "roman", quantity: 1, price: 776, icon: "Cioccolata_da_Hanselmann.jpg" },
    { title: "Biografia del figlio combiato", author: "Andrea Camilleri", category: "roman", quantity: 1, price: 826, icon: "Biografia_del_figlio_combiato.jpg" },
    { title: "L’isola di Arturi", author: "Elsa Morante", category: "roman", quantity: 1, price: 878, icon: "Lisola_di_Artur.jpg" },
    { title: "De Roberto I Vicere", author: "Federico Roberto", category: "roman", quantity: 1, price: 840, icon: "Vicere.jpg" },
    { title: "La madre", author: "Grazia Deledda", category: "roman", quantity: 1, price: 620, icon: "La_madre.jpg" },
    { title: "Caro Michele", author: "Natalia Ginzburg", category: "roman", quantity: 1, price: 826, icon: "Caro_Michele.jpg" },
    { title: "L’armonia del mondo", author: "Pietro Citati", category: "studim / ese", quantity: 1, price: 780, icon: "Larmonia_del_mondo.jpg" },
    { title: "L’edera", author: "Grazia Deledda", category: "roman", quantity: 1, price: 620, icon: "Ledera.jpg" },
    { title: "La scomparsa Di Pato", author: "Andrea Camilleri", category: "roman", quantity: 1, price: 840, icon: "La_scomparsa_Di_Pato.jpg" },
    { title: "Tecniche di seduzione", author: "Andrea de Carlo", category: "roman", quantity: 1, price: 878, icon: "Tecniche_di_seduzione.jpg" },
    { title: "In punta di cuore", author: "Maria Venturi", category: "roman", quantity: 1, price: 750, icon: "In_punta_di_cuore.jpg" },
    { title: "Malombra", author: "Antonio Fogarzzo", category: "roman", quantity: 1, price: 680, icon: "Malombra.jpg" },
    { title: "Mai devi domandarmi", author: "Natalia Gizburg", category: "novela / tregime", quantity: 1, price: 850, icon: "Mai_devi_domandarmi.jpg" },
    { title: "I sommersi e I salvati", author: "Priomo Levi", category: "histori", quantity: 1, price: 720, icon: "I_sommersi_e_I_salvati.jpg" },
    { title: "Il deserto dei Tartari", author: "Dino Buzzati", category: "roman", quantity: 1, price: 680, icon: "Il_deserto_dei_Tartari.jpg" },
    { title: "Voci", author: "Dacia Maraini", category: "roman", quantity: 1, price: 723, icon: "voci.jpg" },
    { title: "L’avventura di un povero crocatio", author: "Franco Cardni", category: "roman", quantity: 1, price: 740, icon: "Lavventura_di_un_povero_crocatio.jpg" },
    { title: "Puerto escondido", author: "Pino Caucci", category: "roman", quantity: 1, price: 740, icon: "puerto.jfif" },
    { title: "La boutique del mistero", author: "Dino Buzzati", category: "novela / tregime", quantity: 1, price: 680, icon: "La_boutique_del_mistero.jpg" },
    { title: "City", author: "Alessandro Baricco", category: "roman", quantity: 1, price: 800, icon: "city.jpg" },
    { title: "Palomar", author: "Etalo Calvino", category: "roman", quantity: 1, price: 740, icon: "palomar.webp" },
    { title: "La gloria", author: "Giuseppe Berto", category: "roman", quantity: 1, price: 723, icon: "la_gloria.jpg" },
    { title: "Fiabe italiane volume prime", author: "Italo Calvino", category: "novela / tregime", quantity: 1, price: null, icon: "I.Calvino-Fiabe-italiane-vol.1.jpg" },
    { title: "Fiabe italiane .Volume secondo", author: "Italo Calvino", category: "novela / tregime", quantity: 1, price: null, icon: "I.Calvino-Fiabe-italiane-Vol.2.jpg" },
    { title: "Fiabe italiane. Volume terzo", author: "Italo Calvino", category: "novela / tregime", quantity: 1, price: null, icon: "I.Calvino-Fiabe-italiane-Vol.3.jpg" },
    { title: "The Haymedow", author: "Gary Paulsen", category: "roman", quantity: 1, price: 599, icon: "The_Haymeadow.jpg" },
    { title: "Il giardino dei Finizi-Contini", author: "Giorgio Bossani", category: "roman", quantity: 1, price: 680, icon: "Il_giardino_dei_Finizi_Contini.jpg" },
    { title: "Mimozat e kujtimeve", author: "Basir Bushkashi", category: "poezi", quantity: 3, price: 800, icon: "📖" },
    { title: "Panoramë Matjane", author: "Hamdi Hysuka", category: "publicistikë", quantity: 5, price: 300, icon: "📖" },
    { title: "Qiejt e brengave", author: "Basir Bushkashi", category: "poezi", quantity: 5, price: 700, icon: "qiejt_e_brengave.jpg" },
    { title: "Zjarre dhe fllad", author: "Basir Bushkashi", category: "poezi", quantity: 4, price: 700, icon: "zjarr_dhe_fllad.jpg" },
    { title: "Trashëgimia iliro-arbërore", author: "Dilaver Kurti", category: "studime", quantity: 5, price: 520, icon: "trashegimi_iliro_arberore.jpeg" },
    { title: "Përtej është qielli", author: "Basir Bushkashi", category: "poezi", quantity: 1, price: 350, icon: "📖" },
    { title: "Liset e fjalës", author: "Basir Bushkashi", category: "poezi", quantity: 4, price: 500, icon: "📖" },
    { title: "Kurora e pikëllimit", author: "Basir Bushkashi", category: "poezi", quantity: 1, price: 500, icon: "📖" },
    { title: "Stinë rinie", author: "Basir Bushkashi", category: "poezi", quantity: 6, price: 500, icon: "📖" },
    { title: "Shkulmet e bardha", author: "Basir Bushkashi", category: "poezi", quantity: 4, price: 600, icon: "📖" },
    { title: "Shpirti i drurëve", author: "Basir Bushkashi", category: "poezi", quantity: 5, price: 500, icon: "shpirti_i_drureve.jpeg" },
    { title: "Antologji e Poezisë Matjane", author: "", category: "antologji", quantity: 2, price: 1000, icon: "antologji_e_poezise_matjane.jpg" },

    { title: "Poetika e Budit", author: "Behar Gjoka", category: "studim / ese", quantity: 2, price: 600, icon: "poetika_e_budid.jpeg" },
    { title: "Orët e ringjalljes", author: "Behar Gjoka", category: "studim / ese", quantity: 3, price: 500, icon: "📖" },
    { title: "Migjeni në pakohësi", author: "Behar Gjoka", category: "studim / ese", quantity: 3, price: 1200, icon: "migjeni_ne_pakohesi.jfif" },
    { title: "Kadare i rilexuar", author: "Behar Gjoka", category: "studim / ese", quantity: 2, price: 800, icon: "kadare_i_rilexuar.jfif" },
    { title: "Kuteli dhe letrarja", author: "Behar Gjoka", category: "studim / ese", quantity: 3, price: 900, icon: "📖" },

    { title: "Shkëlqimi dhe rënia e shokut Zylo", author: "Dritëro Agolli", category: "roman", quantity: 1, price: null, icon: "shkelqimi_dhe_renia_e_shokut_zylo.jpg" },
    { title: "Melodi zemre", author: "Ervisa Ruka", category: "poezi", quantity: 1, price: 300, icon: "📖" },
    { title: "Një pasqyrë jete njerëzore", author: "Jeronim De Rada", category: "poezi", quantity: 2, price: 900, icon: "nje_pasqyre_jete_njerezore.jpg" },
    { title: "Pëllumbesha e qiellit tim", author: "Shyqyri Koci", category: "poezi", quantity: 1, price: 250, icon: "📖" },

    { title: "Gjeniu (botim i plotë)", author: "Teodor Drazjer", category: "biografi", quantity: 1, price: null, icon: "gjeniu_teodor_drajzer.jpg" },
    { title: "Princi i vogël", author: "Antoine de Saint-Exupéry", category: "roman", quantity: 1, price: 700, icon: "princi_i_vogel.jpg" },
    { title: "Lulet e së keqes", author: "Sharl Bodler", category: "poezi", quantity: 3, price: 900, icon: "lulet_e_se_keqes.jpg" },
    { title: "Gjahtarët e gjirafave", author: "Majn Rid", category: "roman aventurë", quantity: 8, price: 400, icon: "gjirafa.jfif" },

    { title: "L’anello di Clarisse", author: "Claudio Magris", category: "roman", quantity: 1, price: 900, icon: "Lanello_di_Clarisse.jpg" },
    { title: "La luna e i falò", author: "Cesare Pavese", category: "roman", quantity: 1, price: 800, icon: "La_luna_e_i_falò.jpg" },
    { title: "La casa in collina", author: "Cesare Pavese", category: "roman", quantity: 1, price: 775, icon: "La_casa_in_collina.jpg" },
    { title: "Lessico famigliare", author: "Natalia Ginzburg", category: "roman", quantity: 1, price: 900, icon: "Lessico_famigliare.jpg" },
    { title: "I Malavoglia", author: "Giovanni Verga", category: "roman", quantity: 1, price: 800, icon: "I_Malavoglia.jpg" },

    { title: "Pajtimi 1 (7) 1998", author: "" , category: "revistë", quantity: 1, price: null, icon: "📘" },
    { title: "Pajtimi 4 (1997)", author: "", category: "revistë", quantity: 1, price: null, icon: "📘" },
    { title: "Analiza dhe interpretime letrare (modele)", author: "", category: "studim / ese", quantity: 1, price: 350, icon: "📘" },
    { title: "Planifikimi i buxhetit të fondeve të shkollës", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Psikologjia 12 – libër mësuesi", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },

    { title: "Biologjia pjesa II (10–11)", author: "", category: "studim / ese", quantity: 2, price: 450, icon: "📘" },
    { title: "Biologjia (10–11)", author: "", category: "studim / ese", quantity: 1, price: 430, icon: "📘" },
    { title: "Biologjia 10", author: "", category: "studim / ese", quantity: 1, price: 270, icon: "📘" },
    { title: "Biologjia 10", author: "", category: "studim / ese", quantity: 1, price: 280, icon: "📘" },
    { title: "Biologjia 11", author: "", category: "studim / ese", quantity: 1, price: 276, icon: "📘" },
    { title: "Biologjia 11", author: "", category: "studim / ese", quantity: 2, price: 270, icon: "📘" },
    { title: "Biologjia 12", author: "", category: "studim / ese", quantity: 2, price: 280, icon: "📘" },

    { title: "Kimia 10", author: "", category: "studim / ese", quantity: 1, price: 290, icon: "📘" },
    { title: "Kimia 10", author: "", category: "studim / ese", quantity: 1, price: 312, icon: "📘" },
    { title: "Kimia 10", author: "", category: "studim / ese", quantity: 3, price: 300, icon: "📘" },
    { title: "Kimia 11", author: "", category: "studim / ese", quantity: 1, price: 270, icon: "📘" },
    { title: "Kimia 11", author: "", category: "studim / ese", quantity: 5, price: 280, icon: "📘" },
    { title: "Kimia 11", author: "", category: "studim / ese", quantity: 2, price: 260, icon: "📘" },
    { title: "Kimia 2", author: "", category: "studim / ese", quantity: 1, price: 400, icon: "📘" },
    { title: "Kimia 2 – ushtrime të zgjidhura", author: "", category: "studim / ese", quantity: 1, price: 400, icon: "📘" },
    
    { title: "Fizika 11", author: "", category: "studim / ese", quantity: 1, price: 280, icon: "📘" },
    { title: "Fizika 11", author: "", category: "studim / ese", quantity: 3, price: 302, icon: "📘" },
    { title: "Fizika 12", author: "", category: "studim / ese", quantity: 1, price: 284, icon: "📘" },
    { title: "Fizika 10", author: "", category: "studim / ese", quantity: 2, price: 305, icon: "📘" },

    { title: "Matematikë 3.1", author: "", category: "studim / ese", quantity: 1, price: 340, icon: "📘" },
    { title: "Matematikë 3.2", author: "", category: "studim / ese", quantity: 1, price: 115, icon: "📘" },
    { title: "Matematikë 4.2", author: "", category: "studim / ese", quantity: 1, price: 200, icon: "📘" },

    { title: "Histori 10", author: "", category: "studim / ese", quantity: 1, price: 185, icon: "📘" },
    { title: "Historia 11", author: "", category: "studim / ese", quantity: 2, price: 356, icon: "📘" },
    { title: "Historia e shqiptarëve 12", author: "", category: "studim / ese", quantity: 1, price: 929, icon: "📘" },
    { title: "Historia e popullit shqiptar 12", author: "", category: "studim / ese", quantity: 1, price: 290, icon: "📘" },
    { title: "Historia e qytetërimeve në antikitet dhe mesjetë", author: "", category: "studim / ese", quantity: 1, price: 165, icon: "📘" },
    { title: "Historia e qytetërimit (PEGI)", author: "", category: "studim / ese", quantity: 1, price: 265, icon: "📘" },

    { title: "Qytetaria 10", author: "", category: "studim / ese", quantity: 1, price: 346, icon: "📘" },
    { title: "Qytetaria 10", author: "", category: "studim / ese", quantity: 2, price: 275, icon: "📘" },
    { title: "Qytetari 11", author: "", category: "studim / ese", quantity: 1, price: 150, icon: "📘" },
    { title: "Qytetari 12", author: "", category: "studim / ese", quantity: 1, price: 380, icon: "📘" },

    { title: "English for You 4", author: "", category: "studim / ese", quantity: 2, price: 350, icon: "📘" },
    { title: "English 4", author: "", category: "studim / ese", quantity: 3, price: 465, icon: "📘" },
    { title: "English for You 2", author: "", category: "studim / ese", quantity: 1, price: 350, icon: "📘" },

    { title: "Atlas i zoologjisë", author: "", category: "enciklopedi", quantity: 1, price: null, icon: "📘" },
    { title: "Atlas themelor i ekologjisë", author: "", category: "enciklopedi", quantity: 2, price: null, icon: "📘" },
    { title: "Atlas themelor i filozofisë", author: "", category: "enciklopedi", quantity: 2, price: null, icon: "📘" },
    { title: "Atlas themelor i botanikës", author: "", category: "enciklopedi", quantity: 1, price: null, icon: "📘" },
    { title: "Atlas i historisë së botës", author: "", category: "enciklopedi", quantity: 2, price: null, icon: "📘" },
    { title: "Atlas i gjeografisë fizike", author: "", category: "enciklopedi", quantity: 1, price: null, icon: "📘" },
    { title: "Atlas themelor i historisë së botës", author: "", category: "enciklopedi", quantity: 2, price: null, icon: "📘" },
    { title: "Libër mësuesi – Sociologjia", author: "", category: "studim / ese", quantity: 1, price: 300, icon: "📘" },
    { title: "Matematika 1", author: "", category: "studim / ese", quantity: 2, price: 350, icon: "📘" },

    { title: "Ushtrime & problema të fizikës", author: "", category: "studim / ese", quantity: 10, price: "360;400", icon: "📘" },
    { title: "Tell Me More – Education Online", author: "", category: "studim / ese", quantity: 9, price: 2900, icon: "📘" },
    { title: "Poezi dhe poemë", author: "", category: "poezi", quantity: 1, price: 800, icon: "📖" },
    { title: "Antologji e mendimit shqiptar", author: "", category: "studim / ese", quantity: 2, price: 1500, icon: "📘" },
    { title: "Enciklopedi e mendimit shqiptar", author: "", category: "enciklopedi", quantity: 6, price: 1500, icon: "📘" },
    { title: "Tell Me More – Education Online Kl. VI", author: "", category: "studim / ese", quantity: 1, price: 2900, icon: "📘" },

    { title: "Tell Me More – Education Online Kl. VII", author: "", category: "studim / ese", quantity: 1, price: 2900, icon: "📘" },
    { title: "Tell Me More – Education Online Kl. VIII", author: "", category: "studim / ese", quantity: 1, price: 2900, icon: "📘" },
    { title: "Tell Me More – Education Online Kl. IX", author: "", category: "studim / ese", quantity: 1, price: 2900, icon: "📘" },
    { title: "Tell Me More – Education Online Kl. XII", author: "", category: "studim / ese", quantity: 25, price: 2900, icon: "📘" },
    { title: "Financat personale në duart e tua", author: "", category: "studim / ese", quantity: 60, price: null, icon: "📘" },
    { title: "Historia e qytetërimit botëror", author: "", category: "studim / ese", quantity: 1, price: 200, icon: "📘" },
    { title: "Gjuha frënge 2", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },

    { title: "Letërsia 12", author: "", category: "studim / ese", quantity: 1, price: 134, icon: "📘" },
    { title: "Letërsia 11", author: "", category: "studim / ese", quantity: 1, price: 530, icon: "📘" },
    { title: "Letërsia me zgjedhje 12", author: "", category: "studim / ese", quantity: 1, price: 733, icon: "📘" },

    { title: "Teatër 10", author: "", category: "studim / ese", quantity: 1, price: 220, icon: "📖" },
    { title: "Teatër 11", author: "", category: "studim / ese", quantity: 1, price: "125 L / 1 €", icon: "📖" },

    { title: "Mësimi me klasa të bashkuara", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Manual trajnimi", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Konceptimi dhe organizimi i punës me klasat kolektive", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Etika e biznesit", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Libër mësuesi – Qytetari 11", author: "", category: "studim / ese", quantity: 1, price: 200, icon: "📘" },
    { title: "Teknologjia 10", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Udhëzues për mësuesit e rinj të shkollave", author: "", category: "studim / ese", quantity: 1, price: 1000, icon: "📘" },
    { title: "Ushtrime e problema fizike", author: "", category: "studim / ese", quantity: 1, price: 400, icon: "📘" },
    { title: "Qytetari", author: "", category: "studim / ese", quantity: 1, price: 330, icon: "📘" },
    { title: "Gjeografi 12", author: "", category: "studim / ese", quantity: 1, price: 300, icon: "📘" },
    { title: "Fizika 11", author: "", category: "studim / ese", quantity: 1, price: 280, icon: "📘" },
    { title: "Artet", author: "", category: "studim / ese", quantity: 1, price: 440, icon: "📘" },

    { title: "Ekonomi e zbatuar – libër ushtrimesh", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Guide për maturën shtetërore", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Raporti vjetor statistikor i arsimit", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Entropia", author: "", category: "studim / ese", quantity: 1, price: 700, icon: "📘" },
    { title: "Gjeografia 11", author: "", category: "studim / ese", quantity: 1, price: 572, icon: "📘" },
    { title: "Trashëgimia jonë kulturore 10", author: "", category: "studim / ese", quantity: 2, price: 254, icon: "📘" },
    
    { title: "Blockbuster", author: "", category: "studim / ese", quantity: 2, price: null, icon: "📘" },
    { title: "New Framework 3", author: "", category: "studim / ese", quantity: 2, price: null, icon: "📘" },
    { title: "Traveller B2", author: "", category: "studim / ese", quantity: 2, price: null, icon: "📘" },
    { title: "Traveller Pre-Intermediate", author: "", category: "studim / ese", quantity: 2, price: null, icon: "📘" },
    { title: "Traveller Intermediate B1", author: "", category: "studim / ese", quantity: 2, price: null, icon: "📘" },
    { title: "Prospects", author: "", category: "studim / ese", quantity: 2, price: null, icon: "📘" },
    { title: "Allegro", author: "", category: "studim / ese", quantity: 2, price: null, icon: "📘" },

    { title: "La lingua pensata", author: "", category: "studim / ese", quantity: 1, price: "16.60 €", icon: "📘" },
    { title: "Le parole, le regole, i testi C", author: "", category: "studim / ese", quantity: 1, price: "28.85 €", icon: "📘" },
    { title: "Le parole, le regole, i testi A", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },

    { title: "Francais", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Francais 4", author: "", category: "studim / ese", quantity: 1, price: 544, icon: "📘" },
    { title: "Francais 4 – cahier d’exercices", author: "", category: "studim / ese", quantity: 1, price: 485, icon: "📘" },
    { title: "Le francais en 5e", author: "", category: "studim / ese", quantity: 3, price: null, icon: "📘" },

    { title: "National Geographic (tituj të ndryshëm)", author: "", category: "revistë", quantity: 1, price: null, icon: "📘" },
    { title: "Mouths and Noses", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "George at the Zoo", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Whistles and Dreams", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },

    { title: "Physics", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Biofizika", author: "", category: "studim / ese", quantity: 1, price: 1200, icon: "📘" },

    { title: "Probleme psikopedagogjike e sociale", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Braktisja e fshehtë (objektiva minimale)", author: "", category: "studim / ese", quantity: 3, price: null, icon: "📘" },
    
    { title: "Arsimi i lartë në Shqipëri 2011", author: "", category: "studim / ese", quantity: 2, price: null, icon: "📘" },
    { title: "Raporte matura shtetërore 2007", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Metodologjia e inspektimit arsimor", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Trëndafila me gjemba", author: "", category: "", quantity: 3, price: 250, icon: "📘" },
    { title: "Më quajnë Musine Kokalari", author: " Persida Asllani", category: "biografi", quantity: 1, price: 600, icon: "musine.jfif" },
    { title: "Fabulat e Ezopit", author: "Ezopi", category: "novela / tregime", quantity: 1, price: 420, icon: "fabulat_ezopit.jpg" },
    { title: "Fëmijët nuk duan psikolog, duan prindër!", author: "", category: "studim / ese", quantity: 2, price: 600, icon: "📘" },
    { title: "3000 Solved Problems in Physics", author: "", category: "studim / ese", quantity: 1, price: 2800, icon: "📘" },
    { title: "Essential Principles of Physics (2nd ed.)", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Never a Worm This Long", author: "", category: "novela / tregime", quantity: 1, price: null, icon: "never_a_worm_this_long.jpg" },
    { title: "Treasury of Literature – Emerald Forest", author: "", category: "antologji", quantity: 1, price: null, icon: "📖" },
    { title: "Treasury of Literature – All Kinds of Friends", author: "", category: "antologji", quantity: 1, price: null, icon: "📖" },
    { title: "Il nostro mondo – Natura d’Italia", author: "", category: "studim / ese", quantity: 1, price: 1800, icon: "📘" },
    { title: "Atlante storico De Agostini", author: "", category: "enciklopedi", quantity: 1, price: 3400, icon: "📘" },
    { title: "Atlante geografico metodico De Agostini (2007–2008)", author: "", category: "enciklopedi", quantity: 4, price: 4000, icon: "📘" },
    { title: "College Physics – One", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "College Physics – Two", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "College Physics – Three", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Lo zingarelli minore", author: "", category: "enciklopedi", quantity: 2, price: "22.5 euro", icon: "📘" },
    { title: "Didattica dell’italiano a stranieri", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" },
    { title: "Senza Ire Toscana", author: "", category: "studim / ese", quantity: 1, price: null, icon: "📘" }
    { title: "Origjina e derës arbërore të Kastriotëve", author: "Mëhill Elezi", category: "studim / ese",quantity: 1, price: "2000" } 
    
];





















